#pragma once

#define KEY_THIS        "this"
#define KEY_SUPER       "super"
#define KEY_TRUE        "true"
#define KEY_FALSE       "false"
#define KEY_STATIC      "static"
#define KEY_VIRTUAL     "virtual"
#define KEY_CONST       "const"
#define KEY_CLASS       "class"

#define KEY_ONE_STD     "one.std"
#define KEY_ONE_OBJECT_CLASS KEY_ONE_STD ".Object"
#define KEY_ONE_INTERFACE_CLASS KEY_ONE_STD ".Interface"
#define KEY_ONE_STRING_CLASS KEY_ONE_STD ".String"
#define KEY_ONE_ARRAY_CLASS  KEY_ONE_STD ".Array"
#define KEY_ONE_ITERABLE_CLASS  KEY_ONE_STD ".Iterable"
#define KEY_ONE_CLASS_CLASS  KEY_ONE_STD ".Class"
#define KEY_ONE_EXCEPTION_CLASS  KEY_ONE_STD ".Exception"

#define KEY_INIT_VAR_FUNC           "__initVar__"
#define KEY_INIT_STATIC_VAR_FUNC    "__initStaticVar__"
#define KEY_DESTRUCT_FUNC           "__destruct__"
#define KEY_CONSTRUCT_FUNC          "__construct__"
#define KEY_CREATE_OBJECT_FUNC      "__createObject__"
#define KEY_CLEAR_VAR_FUNC          "__clearVar__"
#define KEY_DESTROY_FUNC            "__destroy__"

#define KEY_VALUEOF_FUNC            "valueOf"
#define KEY_CLONE_FUNC              "clone"
#define KEY_EQUAL_FUNC              "equal"
#define KEY_COMPARE_FUNC            "compare"
#define KEY_COMBINE_FUNC            "combine"

#define KEY_TAB         "    "